[technote]
id = "RTN-077"
series_id = "RTN"
canonical_url = "https://rtn-077.lsst.io"
github_url = "https://github.com/lsst/rtn-077"
github_default_branch = "main"
date_created = 2024-02-28T20:24:28Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "William"
name.family = "O'Mullane"
internal_id = "omullanew"
orcid = "https://orcid.org/0000-0003-4141-6195"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory"
internal_id = "RubinObsC"
address = "Avenida Juan Cisternas 1500, La Serena, Chile"

[[technote.authors]]
name.given = "Yusra"
name.family = "AlSayyad"
orcid = "https://orcid.org/0009-0008-9216-7516"
[[technote.authors.affiliations]]
name = "Princeton University"
address = "4 Ivy Lane, Princeton NJ 08544"
